### ISSUE TITLE
npm test error

### ISSUE THREAD

**Issue by mmontelaro** [ngand000/nicebreakers#45]
When running npm test, the error:
```
"cookie": this._ownerDocument._cookieJar.getCookieStringSync(nodeParsedURL, { http: true }),    
                                        ^                                                                 
                                                                                                          
TypeError: Cannot read properties of null (reading '_cookieJar')                                          
    at C:\Users\mmont\nicebreakers\node_modules\jsdom\lib\jsdom\living\websockets\WebSocket-impl.js:132:41
    at new Promise (<anonymous>)                                                                          
    at C:\Users\mmont\nicebreakers\node_modules\jsdom\lib\jsdom\living\websockets\WebSocket-impl.js:120:94
    at processTicksAndRejections (node:internal/process/task_queues:95:5)                                 

Node.js v18.16.1
```
happens, which makes it so that the tests cannot run. This seems to be related to npm test running the javascript directly rather than through a browser, so the expected properties of the browser are undefined.

**Comment by mmontelaro** [comment]
update: this doesn't happen when testing smaller components like ActivityPreview. Only testing those is not ideal but it's what we can do until we figure this out

**Comment by shivd04uwedu** [comment]
The CI is now able to run npm test without any issues

**Comment by mmontelaro** [comment]
Running tests with Amplify still causes errors because there is no browser
